#!/usr/bin/env python3
# ============================================================
# FireGod-ESP — Web asset embedder (PlatformIO pre-build hook)
#
# Reads web/{index.html,style.css,app.js}, gzips each, and emits
# src/data/web_assets.h with PROGMEM byte arrays + lengths that
# web_server.cpp serves via beginResponse_P(..., "gzip").
#
# Runs on every build (extra_scripts = pre:scripts/embed_web.py),
# so the WebUI stays editable as normal files.
# ============================================================
import os
import gzip

# Map source file -> C identifier base. web_server.cpp expects:
#   index_html_gz / index_html_gz_len
#   style_css_gz  / style_css_gz_len
#   app_js_gz     / app_js_gz_len
ASSETS = [
    ("index.html", "index_html"),
    ("style.css",  "style_css"),
    ("app.js",     "app_js"),
]


def _emit_array(name, data):
    out = ["const unsigned char %s_gz[] PROGMEM = {" % name]
    line = "  "
    for i, b in enumerate(data):
        line += "0x%02x," % b
        if (i + 1) % 16 == 0:
            out.append(line)
            line = "  "
    if line.strip():
        out.append(line)
    out.append("};")
    out.append("const unsigned int %s_gz_len = %d;" % (name, len(data)))
    out.append("")
    return "\n".join(out)


def build_header(project_dir):
    web_dir = os.path.join(project_dir, "web")
    out_dir = os.path.join(project_dir, "src", "data")
    out_path = os.path.join(out_dir, "web_assets.h")
    os.makedirs(out_dir, exist_ok=True)

    parts = [
        "// AUTO-GENERATED by scripts/embed_web.py — DO NOT EDIT.",
        "// Regenerated on every build from web/*.",
        "#pragma once",
        "",
    ]

    total_raw = 0
    total_gz = 0
    for fname, ident in ASSETS:
        src = os.path.join(web_dir, fname)
        if not os.path.isfile(src):
            raise SystemExit("[embed_web] missing asset: %s" % src)
        with open(src, "rb") as f:
            raw = f.read()
        # mtime=0 -> reproducible output (no rebuild churn).
        gz = gzip.compress(raw, compresslevel=9, mtime=0)
        total_raw += len(raw)
        total_gz += len(gz)
        parts.append("// %s: %d bytes -> %d gz" % (fname, len(raw), len(gz)))
        parts.append(_emit_array(ident, gz))

    new_content = "\n".join(parts)

    # Skip rewrite if unchanged (avoids triggering a full rebuild).
    if os.path.isfile(out_path):
        with open(out_path, "r") as f:
            if f.read() == new_content:
                print("[embed_web] web_assets.h up to date (%d -> %d bytes gz)"
                      % (total_raw, total_gz))
                return

    with open(out_path, "w") as f:
        f.write(new_content)
    print("[embed_web] wrote %s (%d -> %d bytes gz)" % (out_path, total_raw, total_gz))


# --- PlatformIO entry: `Import("env")` is available in build context ---
try:
    Import("env")  # noqa: F821  (provided by SCons/PlatformIO)
    build_header(env.subst("$PROJECT_DIR"))  # noqa: F821
except NameError:
    # Allow standalone run: `python3 scripts/embed_web.py`
    if __name__ == "__main__":
        here = os.path.dirname(os.path.abspath(__file__))
        build_header(os.path.dirname(here))
